[workspace]
authors = ["Vladim√≠r Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "zarr_segmentation_and_tracking_for_Mastodon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
trackastra = ">=0.3.2,<0.4"
cellpose = "<4.0"
aiohttp = ">=3.13.3,<4"
s3fs = ">=2026.1.0,<2027"
napari = ">=0.6.6,<0.7"
pyqt = ">=5.15.11,<6"

[pypi-dependencies]
ngff_zarr = ">=0.20.0"

