[workspace]
authors = ["Vladim√≠r Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge", "bioconda"]
name = "nextflow"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
groovy = ">=4_0_24,<5"
nextflow = ">=25.10.0,<26"
